## 3. Fit the model/ algorithm on our data and use it to make a prediction

### 3.1 fitting the model to the data 

different names for:

* 'X' = featuress, features variables, data

* 'y' = labels, targets, target variables

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [3]:
hd = pd.read_csv('heart-disease.csv')
hd.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [4]:
# random forest classifier

from sklearn.ensemble import RandomForestClassifier
np.random.seed(42)

X = hd.drop('target', axis = 1)
y = hd['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

clf = RandomForestClassifier(n_estimators = 100)

# fit the model to the data (train the machinne learning model)
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.8524590163934426

### 3.2 make prediction using a ML model

two ways to make prediction

1. `predict`

2. `predict_proba()`

In [5]:
# use a trained model to make predictions

#here's an example that doesn't work
clf.predict(np.array([1,7,8,3,5, 7,2,45,5]))

ValueError: Expected 2D array, got 1D array instead:
array=[ 1.  7.  8.  3.  5.  7.  2. 45.  5.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [6]:
clf.predict(X_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [7]:
np.array(y_test)

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [8]:
#after predicting the results, then comparing predictions to truth labels to evaluate the model
y_preds = clf.predict(X_test)
np.mean(y_preds == y_test)

0.8524590163934426

In [9]:
clf.score(X_test, y_test)

0.8524590163934426

In [10]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_preds)

0.8524590163934426

make decisions with `predict_proba()`

In [14]:
#predict_proba() returns probability of a classification label = the possibility of having a heart dicease or not

clf.predict_proba(X_test[:5])

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82]])

In [16]:
'''
predict function only gives you the results, 
the result here means the algorithm thinks that the first set of 
data has a higher probability  of having the result of '0'
'''
clf.predict(X_test[:5])

array([0, 1, 1, 0, 1])

### predict with a regression model ( boston house )

In [17]:
#import boston housing dataset
from sklearn.datasets import load_boston
boston = load_boston()
boston_df = pd.DataFrame(boston["data"], columns = boston["feature_names"])
boston_df["target"] = pd.Series(boston["target"])
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [27]:
from sklearn.ensemble import RandomForestRegressor
np.random.seed(42)
X = boston_df.drop('target', axis = 1)
y = boston_df['target']

X_train, X_test,y_train, y_test = train_test_split(X, y, test_size = 0.2)

model = RandomForestRegressor(n_estimators = 100)

model.fit(X_train, y_train)
model.score(X_test, y_test)



0.873969014117403

In [32]:
# make predictions

y_preds = model.predict(X_test)

y_preds[:5]

array([23.002, 30.826, 16.734, 23.467, 16.853])

In [34]:
np.array(y_test[:5])

array([23.6, 32.4, 13.6, 22.8, 16.1])

In [35]:
#compare the predictions to the truth

from sklearn.metrics  import mean_absolute_error
mean_absolute_error(y_test, y_preds)

# on average the difference between truth and prediction

2.1226372549019623

## next  step: evaluating the model